### ISSUE TITLE
Where to start?

### ISSUE THREAD

**Issue by VegetaDTX** [salu133445/musegan#107]
Hello @salu133445 and the rest of the crew :)

First off, I would like to thank you for sharing this project as an open source one!
I think you've done an amazing job with this project.

However, I'm a bit confused as to what exactly I should focus on if I want to start off from the most recent or the most well optimized base? Would you actually recommend going for bmusegan?

musegan/V2 seems like a great start that's much more simplified and seems just as recent (and I think I'm having success porting it to Google Colab), but then it says there: "Warning: this version is no longer maintained", so I'm confused. Does that statement refer to musegan in general (as being replaced by bmusegan) or just to the musegan in the V2 folder?

I apologize if this was not the right place to ask questions like these, but I assumed it is ok, since I've read other posts here in the issues. Please bear with my newbiness about how to use Github, I'm both forking and posting an issue for the first time ever :)

**Comment by salu133445** [comment]
Hi, thanks for the question! Both v3 (latest) and v2 include the BinaryMuseGAN model, where v3 is more modularized for comparing different models, while v2 is more easy to follow. I would suggest you to go for the latest version (v3) as it comes with Pipfile for explicit dependencies (see README), but we do not keep the requirement.txt or Pipfile for v1 and v2 when we released them. Feel free to let me know if you have any other questions. Thank you.

**Comment by VegetaDTX** [comment]
Thank you very much for your reply! You are very kind.

Well here are my (perhaps dumb/newbie-like) additional questions :)

1. Where exactly is the v3? :) I don't see a v3 folder anywhere. Is the v3 maybe the main folder itself (musegan)?

2. I still don't understand the real meanings of "inference" and "interpolation" in the context of this project. My assumption is that inference is just a random generation of the samples by AI based on the training data, and Interpolation is some kind of less random generation that generates first sample randomly and then every following sample is just a different version of that first one. I am probably wrong, am I?

3. I have no idea how to use accompanying and conditioning. In params.yaml there is a field "conditioned_track_idx",  but based on the example you pointed to in some of the comments (accompaniment/bass/params.yaml) it seems that one just provides an integer number as the value. Is that number essentually an ID or an index that points to the song in the training data set?

I apologize for so many possibly dumb questions, I'd really appreciate your answers as I am very interested in your project.

**Comment by salu133445** [comment]
Hi,

1. Yes. v3 is what in the the root directory.
2. You might find [this](https://github.com/salu133445/musegan/issues/79#issuecomment-503490677) helpful.
3. The accompaniment takes one specific track as the input and aims to generate the other tracks, and the value `conditioned_track_idx` is the index of that given track.

Thanks.

**Comment by VegetaDTX** [comment]
Thank you sooo much! Can't wait to come home to try it all out! :)
